name: Bypass
description: Report bypasses here
labels: ["bypass"]
body:
  - type: textarea
    attributes:
      label: Describe the bypass and how to replicate it
      description: Provide a video, or detailed instructions to help replicate it.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Grim version
      description: |
        Git commit or the version in the jar's name
    validations:
      required: true

  - type: textarea
    attributes:
      label: Server version
      description: |
        Run `/version` on your server and paste the full, unmodified output here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugins
      description: |
        List all plugins running on your server. To list plugins, run `/plugins`.
    validations:
      required: true