name: False positive
description: Report a false positive here
labels: ["false positive"]
body:
  - type: textarea
    attributes:
      label: Describe the false positive and how to replicate it
      description: |
        Video is always useful. /grim log is required for reporting simulation falses.
        Use /grim verbose and /grim log to get the debug information.
        For non-simulation falses, a minimally reproducable description is best.
    validations:
      required: true

  - type: input
    attributes:
      label: Grim version
      description: |
        Git commit or the version in the jar's name
    validations:
      required: true

  - type: input
    attributes:
      label: Server version
      description: |
        Run `/version` on your server.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugins
      description: |
        List all plugins running on your server. To list plugins, run `/plugins`.
    validations:
      required: true