# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Run Spigot BuildTools for NMS if required
    - name: Setup BuildTools
      run: mkdir BuildTools
    - name: Download BuildTools
      run: wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    - name: 1.16.5
      run: cd BuildTools && java -jar BuildTools.jar --rev 1.16.5
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: mkdir staging && cp target/grim.ac*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
